### ISSUE TITLE
[Warning missing module source file

### ISSUE THREAD

**Issue by CarolineBoyer** [antvis/G2Plot#1129]
My apologies if this has been asked before. 
It might be like #874 ... Not sure

When starting my project after installing the project using `npm install @antv/g2plot` I then have a LOT of warning.

such as 
```
./node_modules/@antv/component/esm/axis/overlap/auto-ellipsis.js
Cannot find source file '../../../src/axis/overlap/auto-ellipsis.ts': Error: Can't resolve '../../../src/axis/overlap/auto-ellipsis.ts' in <PATHTO>\node_modules\@antv\component\esm\axis\overlap'
```

I tried computing the list
axis/overlap/auto-ellipsis
axis/overlap/auto-hide
axis/overlap/auto-rotate
axis/overlap/index.js
shape/marker/index
esm/shape/marker/symbols.js
g-canvas/esm/util/in-path/point-in-path.js
g-canvas/esm/util/in-path/polygon.js
/g-canvas/esm/util/in-stroke/arc.js
g-canvas/esm/util/in-stroke/line.js
g-canvas/esm/util/in-stroke/polyline.js
g-canvas/esm/util/in-stroke/rect-radius.js
g-canvas/esm/util/in-stroke/rect.js
g-base/esm/abstract/base.js
g-base/esm/abstract/canvas.js
component/esm/abstract/component.js
component/lib/abstract/component.js
g-base/esm/abstract/container.js
g-base/esm/abstract/element.js
component/esm/abstract/group-component.js
g-base/esm/abstract/group.js
component/esm/abstract/html-component.js
component/lib/abstract/html-component.js
g-base/esm/abstract/shape.js
/adjust/esm/adjusts/adjust.js
...
and about 50 more like that...

Any clue on what's happening ? Am i missing a package or something ?

I just followed the installation documentation !

**Comment by paleface001** [comment]
sorry, the reason of the install error was because the latest version of @antv/components set to a beta version, which was corrected already.  You can try to install your project now.

**Comment by CarolineBoyer** [comment]
Just to make sure, I should redo a 
`npm install @antv/g2plot`  (I believe it installs @antv/g2plot@1.1.4 )
and relaunch my project that has this package in its node_modules ?

Or do I also need to update @antv/components by doing an `npm install @antv/components@latest` ?

**Comment by CarolineBoyer** [comment]
I am sorry but this is not a close matter for me, I still have the errors coming up.
